import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";

import { useState } from "react";

// Components
import Card from "../components/Card";
import ProjectImage from "../components/ProjectImage";

// Images
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import memoji from "../public/memoji.png";
import design from "../public/design.png";
import code from "../public/code.png";

export default function Home() {
  const tools = ["Photoshop", "Figma", "Illustrator"];
  const languages = ["Javascript", "C#", "Swift"];

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bartu Gençcan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              bartugenccandev
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl dark:text-white"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Bartu Gençcan
            </h2>
            <h3 className=" text-2xl py-2 md:text-3xl dark:text-white">
              Web Developer.
            </h3>
            <p className="text-md py-5 leading-7 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Hard working developer and a team player that has passion for Web
              Development. I have a deep understanding in Javascript, React and
              algorithms.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://www.twitter.com/bartugenccan">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/bartugenccan">
              <AiFillLinkedin />
            </a>
            <a href="https://www.github.com/bartugenccan">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-12 overflow-hidden md:h-96 md:w-96">
            <Image src={memoji} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-600">
              Services I offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my career, I have been working on a wide
              range of projects in the software development industry. I have
              worked with startups, companies and collaborated with talented
              people to create digital products for both business and my self
              improvement.
            </p>
          </div>
          <div className="md:flex md:justify-center gap-3">
            <Card
              image={design}
              header={"Designs To Code"}
              text={
                "I've improved myself to implement desings to code pixel perfect."
              }
              toolsHeader={"Tools I use"}
              tools={tools}
            />
            <Card
              image={code}
              header={"Coding and Algorithms"}
              text={
                "Since the beginning of my programming career I've always tried to improve my algorithm thinking and I've worked with Javascript, C# and Swift."
              }
              toolsHeader={"Languages I use"}
              tools={languages}
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-600">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I've improved myself by developing projects and working with
              teams.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <ProjectImage
              image={web1}
              link="https://github.com/bartugenccan/NetflixClone"
            />
            <ProjectImage
              image={web2}
              link="https://github.com/bartugenccan/valorant-wiki"
            />
            <ProjectImage
              image={web3}
              link="https://github.com/bartugenccan/typing_speed"
            />
            <ProjectImage
              image={web4}
              link="https://github.com/bartugenccan/dummy-defi"
            />
            <ProjectImage
              image={web5}
              link="https://github.com/bartugenccan/disney-plus-clone"
            />
          </div>
        </section>
      </main>
    </div>
  );
}
